{
 "title": "DHIS2",
 "description": "DHIS2 Dashboard",
 "tags": [
  "DHIS2",
  "DHIS2_exporter",
  "micrometer"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Hibernate Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Transactions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "hibernate_transactions_total{instance=\"$instance\", result=\"success\"}"
    }
   ]
  },
  {
   "title": "Prepared Statements ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "hibernate_statements_total{application=\"$application\", status=\"prepared\"}",
     "legendFormat": "Statements"
    }
   ]
  },
  {
   "title": "Total Optimistic Locking Failures per interval",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(hibernate_optimistic_failures_total[$__range])"
    }
   ]
  },
  {
   "title": "Total Query Executions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "hibernate_query_executions_total"
    }
   ]
  },
  {
   "title": "Total Transactions per interval",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(hibernate_transactions_total{instance=\"$instance\", result=\"success\"}[$__range])"
    }
   ]
  },
  {
   "title": "Prepared Statements  pr interval",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(hibernate_statements_total{application=\"$application\", status=\"prepared\"}[$__range])",
     "legendFormat": "Statements"
    }
   ]
  },
  {
   "title": "Total Optimistic Locking Failures",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "hibernate_optimistic_failures_total"
    }
   ]
  },
  {
   "title": "Total Query Executions per interval",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(hibernate_query_executions_total[$__range])"
    }
   ]
  },
  {
   "title": "Entity Manager / Session Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(hibernate_sessions_open_total[2m])  ",
     "legendFormat": "sessions_opened"
    },
    {
     "expr": "rate(hibernate_sessions_closed_total{instance=\"$instance\"}[2m])  ",
     "legendFormat": "sessions_closed"
    },
    {
     "expr": "rate(hibernate_flushes_total{instance=\"$instance\"}[5m])  ",
     "legendFormat": "flushes"
    }
   ]
  },
  {
   "title": "Entity Collection Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(hibernate_collections_loads_total{instance=\"$instance\"}[2m])",
     "legendFormat": "collections loaded"
    },
    {
     "expr": "rate(hibernate_collections_updates_total{instance=\"$instance\"}[2m])",
     "legendFormat": "collections updated"
    },
    {
     "expr": "rate(hibernate_collections_fetches_total{instance=\"$instance\"}[2m])",
     "legendFormat": "collection fetches"
    },
    {
     "expr": "rate(hibernate_collections_deletes_total{instance=\"$instance\"}[2m])",
     "legendFormat": "remove"
    },
    {
     "expr": "rate(hibernate_collections_recreates_total{instance=\"$instance\"}[2m])",
     "legendFormat": "recreates"
    }
   ]
  },
  {
   "title": "Entity Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(hibernate_collections_loads_total{instance=\"$instance\"}[1m])",
     "legendFormat": "entities loaded"
    },
    {
     "expr": "rate(hibernate_entities_updates_total{instance=\"$instance\"}[1m])",
     "legendFormat": "entities updated"
    },
    {
     "expr": "rate(hibernate_entities_fetches_total{instance=\"$instance\"}[1m])",
     "legendFormat": "entities fetched"
    },
    {
     "expr": "rate(hibernate_entities_deletes_total{instance=\"$instance\"}[1m])",
     "legendFormat": "entities removed"
    },
    {
     "expr": "rate(hibernate_entities_recreates_total{instance=\"$instance\"}[1m])",
     "legendFormat": "recreates"
    },
    {
     "expr": "rate(hibernate_entities_inserts_total{instance=\"$instance\"}[1m])",
     "legendFormat": "entities inserted"
    }
   ]
  },
  { "title": "HTTP Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Success Request Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_count{instance=\"$instance\", uri!~\".*actuator.*|.*metrics.*|REDIRECTION\", status=\"200\"}[5m]) != 0",
     "legendFormat": "{{method}} - {{uri}}"
    }
   ]
  },
  {
   "title": "Success Response Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(irate(http_server_requests_seconds_sum{instance=\"$instance\", exception=\"None\", uri!~\".*actuator.*|.*metrics.*\", status=\"200\"}[5m]) > 0) / (irate(http_server_requests_seconds_count{instance=\"$instance\", exception=\"None\", uri!~\".*actuator.*|.*metrics.*\", status=\"200\"}[5m]) > 0)",
     "legendFormat": "{{method}} - {{uri}}"
    }
   ]
  },
  { "title": "C3P0", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jdbc_connections_min{name=\"dataSource\"}",
     "legendFormat": "Min Connections"
    },
    {
     "expr": "jdbc_connections_max{name=\"dataSource\"}",
     "legendFormat": "Max Connections"
    }
   ]
  },
  {
   "title": "C3P0 Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(jdbc_connections_idle[5m])  ",
     "legendFormat": "Idle Connections {{name}}"
    },
    {
     "expr": "rate(jdbc_connections_active[5m])  ",
     "legendFormat": "Active Connections {{name}}"
    }
   ]
  }
 ]
}