{
 "title": "Windows-Dashboard",
 "tags": [
  "Prometheus",
  "windows_exporter",
  "Windows"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(windows_cs_hostname,instance)"
    }
   },
   {
    "name": "show_hostname",
    "label": "Show Hostname",
    "query": {
     "query": "label_values(windows_cs_hostname{job=~\"$job\",instance=~\"$instance\"}, hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "windows_os_time{instance=\"$instance\"} - on() windows_process_start_time_seconds_timestamp{process=\"Idle\", process_id=\"0\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Logical Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_cs_logical_processors{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(windows_cpu_time_total{mode=\"idle\", instance=~\"$instance.*\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-(windows_os_physical_memory_free_bytes{instance=~\"$instance\"} / windows_cs_physical_memory_bytes{instance=~\"$instance\"})*100"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(windows_logical_disk_size_bytes{volume!~\"Harddisk.*\", instance=\"$instance\"}) by (instance) - sum(windows_logical_disk_free_bytes{volume!~\"Harddisk.*\", instance=\"$instance\"}) by (instance)) / sum(windows_logical_disk_size_bytes{volume!~\"Harddisk.*\", instance=\"$instance\"}) by (instance) * 100"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(windows_net_bytes_total{instance=\"$instance\"}[1m])) > 1)* 8"
    }
   ]
  },
  {
   "title": "Disk Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_logical_disk_size_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_cs_physical_memory_bytes{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(windows_cpu_time_total{mode=\"idle\", instance=~\"$instance.*\"}[1m])) * 100)",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(mode) (rate(windows_cpu_time_total{instance=~\"$instance\", mode!=\"idle\"}[1m])) * 100",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Memory details",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "windows_cs_physical_memory_bytes{instance=~\"$instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Total Physical Memory",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "windows_os_physical_memory_free_bytes{instance=~\"$instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Total Free Memory",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "windows_os_virtual_memory_bytes{instance=~\"$instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Virtual memory",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "windows_os_virtual_memory_free_bytes{instance=~\"$instance\"}",
     "legendFormat": "Free virtual memory"
    }
   ]
  },
  {
   "title": "Top 10 Mem Usage per Procecss",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "topk(10, windows_process_working_set_bytes{process!=\"Idle\"})",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "__auto",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Top 10 CPU Usage per Procecss",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "topk(10, sum by(process)(rate(windows_process_cpu_time_total{mode=~\"user|privileged\", process !~\"Idle\",instance=~\"$instance\"}[1m])) *100)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "__auto",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Remaining Disk Space",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "windows_logical_disk_free_bytes{instance=~\"$instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Residual Space {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "windows_logical_disk_size_bytes{instance=~\"$instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Total Space {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "rate(windows_logical_disk_reads_total{instance=~\"$instance\",volume!~\"HarddiskVolume.+\"}[1m])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{volume}} Total Reads",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "rate(windows_logical_disk_writes_total{instance=~\"$instance\",volume!~\"HarddiskVolume.+\"}[1m])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{volume}} Total Writes",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Disk Read/Write",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "rate(windows_logical_disk_read_bytes_total{instance=~\"$instance\",volume!~\"HarddiskVolume.+\"}[1m])\r\n",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": " {{volume}} Reads",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "rate(windows_logical_disk_write_bytes_total{instance=~\"$instance\",volume!~\"HarddiskVolume.+\"}[1m])\r\n",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{volume}} Writes",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "rate(windows_net_bytes_sent_total{instance=~\"$instance\", nic!~\"isatap.*|VPN.*\"}[1m]) * 8 > 0",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{nic}}-Sent",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "rate(windows_net_bytes_received_total{instance=~\"$instance\", nic!~\"isatap.*|VPN.*\"}[1m]) * 8",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{nic}}-Received",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "rate(windows_net_bytes_sent_total{instance=~\"$instance\"}[1m]) > 0",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Sent- Upload",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "- rate(windows_net_bytes_received_total{instance=~\"$instance\"}[1m]) < 0",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Received- Download",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Network Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "  rate(windows_net_bytes_total{instance=~\"$instance\"}[1m]) / windows_net_current_bandwidth_bytes{instance=~\"$instance\"} * 100",
     "legendFormat": "{{nic}}"
    }
   ]
  },
  {
   "title": "Network discarded/error packets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "rate(windows_net_packets_outbound_discarded_total{instance=~\"$instance\", nic!~\"isatap.+\"}[1m]) + rate(windows_net_packets_outbound_errors_total{instance=~\"$instance\"}[1m])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "outbound",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "rate(windows_net_packets_received_discarded_total{instance=~\"$instance\", nic!~\"isatap.+\"}[1m]) + rate(windows_net_packets_received_errors_total{instance=~\"$instance\"}[1m])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "received",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  }
 ]
}